### PR TITLE
MACF-22: Disable auto filling on Create New Device Form

### PR DESCRIPTION
**Pull request by FerjoCode**

### CODE REVIEW

**Comment by azefiel** [comment]
Hey @FerjoCode 

Unfortunately, `autocomplete`'s [behavior](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion) is not uniform across browsers.

That's why we are using `monster.ui#disableAutofill` to obfuscate `name` attributes.

Let me know if you have questions regarding that helper.

**Comment by FerjoCode** [comment]
Thanks @guillegr123! I have already resolved the requested changes, but I'm going to keep `autocomplete="new-password"` for password fields, because this way `monster.ui#disableAutofill` works correctly disabling autofilling in all form fields

**Comment by guillegr123** [comment]
Excellent! About `autocomplete="new-password"` for password fields, I don't think it is necessary. I have done some tests without that attribute in Chrome and Firefox, and the passwords do not seem to be auto-filled by the browser. In fact it is the app who sets a random password every time you want to add a new device. The browser also does not display the saved logins suggestions, as it did before:

image

However, the passwords are not hidden anymore. The behavior before this change was the following:

1. Password is hidden (hidden chars are displayed)
image

2. On focus, password is displayed, to be edited.
image

3. On blur (focus lost), password is hidden again.

This behavior is added by `monster.ui#protectField`, but it does not seem to interact properly with `monster.ui#disableAutofill`.

**Comment by FerjoCode** [comment]
Thanks! I think the problem with `monster.ui#protectField` is because it needs a password field type to work propertly, and `monster.ui#disableAutofill` changes the type for password fields to text

Regarding password fields, I'm actually presenting the auto fill issue in Chrome for `password` and also `mac_address` fields, this happens when `autocomplete="new-password"` is removed from form

image

**Comment by guillegr123** [comment]
Looks good, but I'm not sure if Product Team would agree with the behavior, as the password will no longer be visible to the user. @FerjoCode can you check this with Vladimir?

**Comment by vlad88sv** [comment]
Hi @azefiel do you think we can merge this? - it will work the same as _**Adv. Provisioner**_ at least until [MSTR-167](https://2600hz-commercial.atlassian.net/browse/MSTR-167) is fixed.

And this will unblock us to proceed with MACF-24

--

Thank you @guillegr123 for your excellent peer review!

**Comment by azefiel** [comment]
Looks good to me @vlad88sv 

Not sure how this work is blocking MACF-24 though?

**Comment by vlad88sv** [comment]
Thank you @azefiel! - oh and it block us just because we avoid to edit the same set of files on different PRs

@FerjoCode we are good with this change then :)

**Comment by azefiel** [comment]
Haha, we're not in 2000 anymore, `git` gives the ability for several people to edit the same file concurrently. If merging is too complicated for `git` to handle automatically, a "diff" is created to manually take care of it.

In any case, the files edited in this PR and required to be edited for MACF-24 are not the same so you can have your devs start working on that, no problem.

You should not have to wait to assign tickets based on fear of diffs. `git` is a powerful tool and can be confusing sometimes so I highly recommend [becoming familiar with it](https://git-scm.com/book/en/v2) rather than be scared of it. As always, if you guys have any questions or come upon a merge that's too hard to reconcile, let me know and I'll do my best to explain and/or deal with it as cleanly as possible.

**Comment by FerjoCode** [comment]
Thank you guys! Just lets wait for @guillegr123 's changes approval to get this merged :)

**Comment by vlad88sv** [comment]
Thank you for the advise @azefiel ! haha yeah we just don't want to break anything but we will learn more about it for any future work :)

**Pull request merged**
