### PR TITLE
Add viewing of callflow via click of tile label

### PR DESCRIPTION
**Pull request by mira-t**
I am not completely satisfied with the way I have implemented this change and I would very much appreciate suggestions about how I can improve it. Thank you very much in advance.

### CODE REVIEW

**Comment by JRMaitre** [comment]
Hi, 

I looked at your changes but I don't understand what you're trying to do. Could you explain it here?

Sorry for the delay on this!
JR

**Comment by mira-t** [comment]
Hi,

A user may want to click on a link to another callflow element and see that callflow. What I have done is added a click event handler that puts the callflow's name into the search bar and clicks the first match, thus opening the callflow. However, I feel like there is a better way to implement this. Issues I can see are that users will lose any changes they have made to their current callflow once they navigate away. Furthermore, pagination is not handled and using the search bar is a somewhat hacky approach.

I also wonder if it would be better for the callflow to open in a popup on click instead of opening normally on click? My only concern is that if there is a lot of nesting the user could potentially open lots of popups, which isn't very pleasant.

**Comment by JRMaitre** [comment]
Thank you, I understand now! 

I think what you're trying to do is a good idea, as it would be nice to be able to get more context when editing a callflow. However I agree that its current implementation seems a little funky, and I would rather have the callflow be displayed in a "view-only" popup maybe or something like that.

It will be hard to display some complicated callflows in popup in a very user-friendly way but with the current (very old) architecture of the callflow app, it seems like the path of least resistance.

**Comment by mira-t** [comment]
Thank you very much for the feedback!

The additional context provided by a "view-only" popup is great. A user might also want to go to the callflow from the popup and edit it. Should there be a button in the popup that closes the popup and navigates to the callflow so that they can edit it?

**Comment by JRMaitre** [comment]
Yes I think that could be a good idea too!

**Pull request closed without merging**
