### PR TITLE
MACF-60: Make branch variable's ID optional

### PR DESCRIPTION
**Pull request by guillegr123**

### CODE REVIEW

**Review by azefiel — COMMENTED** [review]
Looks good!

My only worry is, `branch_variable[id=*]`/`branch_variable[]` are pointing to the same object (and it looks like `Branch#setMetadata` mutates it?). Maybe we could use a function to return the config object rather than a variable directly? 

What's your opinion on this matter?

**Comment by guillegr123** [comment]
Hi @azefiel . Thanks. About having both actions pointing to the same object, I checked the code, and it seems that that specific object is not mutated, only the `Branch` instance that is passed as a `node` parameter. I also ran some tests having 3 branch variable nodes in a single callflow, and they don't interfere themselves and the callflow object is generated properly.

However, there may be other scenarios happening behind the scenes, so having a function to create a new config object for each action could be the safest way to avoid any data conflicts, just in case. I think I'll add that function. Is it OK for you?

**Comment by azefiel** [comment]
> However, there may be other scenarios happening behind the scenes, so having a function to create a new config object for each action could be the safest way to avoid any data conflicts, just in case. I think I'll add that function. Is it OK for you?

My thoughts exactly, better to play it defensively as most of this code was not written with mutation and side effects in mind.

**Comment by guillegr123** [comment]
Done @azefiel

**Review by azefiel — APPROVED** [review]
Looks good, merge away!

**Pull request merged**
