### PR TITLE
Add callflow preview feature on click of node

### PR DESCRIPTION
**Pull request by mira-t**
A new, tidier pull request for https://github.com/2600hz/monster-ui-callflows/pull/22. Linter fixes are included in a separate commit from the functionality changes.

### CODE REVIEW

**Comment by mira-t** [comment]
Thank you for the feedback! I have now updated the css to override the default padding.

**Comment by mira-t** [comment]
Hi JR, any updates?

**Comment by JRMaitre** [comment]
Sorry for the delay, thanks for the reminder and for the contribution :)

**Comment by mira-t** [comment]
Thank you very much for your help and for accepting my pull request!

**Pull request merged**
