### PR TITLE
Use gender-neutral pronouns in UI

### PR DESCRIPTION
**Pull request by jkingsman**

### CODE REVIEW

**Comment by JRMaitre** [comment]
I understand we want to change the strings to be gender-neutral, but `Allow this user to call themselves` doesn't sound right to me. Would you have any other suggestion?

**Comment by jkingsman** [comment]
Hmm I think that's the grammatically correct usage per [this (see 3)](https://en.oxforddictionaries.com/definition/themselves). You could also use themself which is less common and apparently even flagged by my spellchecker as not a word, or "him or herself" but I'm a bigger fan of the more inclusive "themselves". Up to you; sounds fine to me.

**Comment by JRMaitre** [comment]
Well I learned something today so thank you for the link :) 

I'll go ahead and merge this, thanks for all the PRs on this, we really appreciate it as we never really took enough time to fix these small (but important!) issues.

Cheers,
JR

**Comment by jkingsman** [comment]
Happy to help out! 🙂

**Pull request merged**
