### PR TITLE
UI-3111: Added privacy to callflow editor

### PR DESCRIPTION
**Pull request by sergey-safarov**

### CODE REVIEW

**Comment by sergey-safarov** [comment]
This is requires merged https://github.com/2600hz/kazoo/pull/4915

**Comment by sergey-safarov** [comment]
Customer is requested to ability to reset privacy via callflow.
Think i will update this PC sun.

**Comment by azefiel** [comment]
I will wait until the related Kazoo PR is merged and deployed to our sandbox before reviewing this.

**Comment by azefiel** [comment]
Feel free to reopen once the related `kazoo` PR is accepted.

**Pull request closed without merging**
