### PR TITLE
[5.1] MACF-78: Fix button being greyed out when creating a time-of-day rule

### PR DESCRIPTION
**Pull request by Isaac2600Hz**

### CODE REVIEW

**Review by ramandeepromana — APPROVED** [review]
Approving as back port for original PR against master https://github.com/2600hz/monster-ui-callflows/pull/246

**Review by ramandeepromana — CHANGES_REQUESTED** [review]
PR looks to be missing the `.circleci/config.yml` change compared to https://github.com/2600hz/monster-ui-callflows/pull/246 and https://github.com/2600hz/monster-ui-callflows/pull/248

**Comment by Isaac2600Hz** [comment]
@ramandeepromana Not needed for 5.1 it was added for 5.2 because the build was failing :)

**Review by ramandeepromana — APPROVED** [review]

**Comment by ramandeepromana** [comment]
Ah 😅 my bad/approved

**Pull request merged**
